export interface Property {
  id: string;
  address: string;
  city: string;
  state: string;
  zip: string;
  price: number;
  beds: number;
  baths: number;
  sqft: number;
  dom: number;
  // Agent / listing info
  agent: string;
  agentName: string;
  agentPhone: string;
  agentEmail: string;
  brokerage: string;
  // Media
  img: string;
  photos: string[];
  // AI / market fields
  type: string;
  priceHistory: string;
  priceChange: number;
  aiScore: number;
  aiLabel: string;
  aiColor: string;
  suggestedOffer: number[];
  marketTrend: string;
  // Dashboard display
  reduced: boolean;
  // MLS listing status
  status?: "Active" | "Pending" | "Sold" | "Withdrawn";
}

// loremflickr.com — real keyword-filtered photos, deterministic with ?lock=N, no auth required
function ext(seed: number, w = 800, h = 600) {
  return `https://loremflickr.com/${w}/${h}/house,exterior?lock=${seed}`;
}
function interior(category: string, seed: number, w = 800, h = 600) {
  return `https://loremflickr.com/${w}/${h}/${category}?lock=${seed}`;
}
function p(extSeed: number, intCategory: string, intSeed: number): string[] {
  return [ext(extSeed), interior(intCategory, intSeed), interior('bedroom', intSeed + 50)];
}

export const ALL_PROPERTIES: Property[] = [
  {
    id: "1",
    address: "2847 N Clark St",
    city: "Chicago",
    state: "IL",
    zip: "60657",
    price: 485000,
    beds: 3,
    baths: 2,
    sqft: 1850,
    dom: 12,
    agent: "Sarah Johnson",
    agentName: "Sarah Johnson",
    agentPhone: "(312) 555-0192",
    agentEmail: "sarah.johnson@coldwellbanker.com",
    brokerage: "Coldwell Banker",
    img: ext(1, 600, 400),
    photos: p(1, 'kitchen', 1),
    type: "Single Family",
    priceHistory: "reduced",
    priceChange: -15000,
    aiScore: 87,
    aiLabel: "Great Value",
    aiColor: "text-blue-700 bg-blue-50",
    suggestedOffer: [475000, 492000],
    marketTrend: "hot",
    reduced: true,
    status: "Active",
  },
  {
    id: "2",
    address: "1520 W Wrightwood Ave",
    city: "Chicago",
    state: "IL",
    zip: "60614",
    price: 625000,
    beds: 4,
    baths: 2.5,
    sqft: 2400,
    dom: 5,
    agent: "Linda Park",
    agentName: "Linda Park",
    agentPhone: "(312) 555-0341",
    agentEmail: "lpark@bairdwarner.com",
    brokerage: "Baird & Warner",
    img: ext(2, 600, 400),
    photos: p(2, 'kitchen', 2),
    type: "Townhouse",
    priceHistory: "same",
    priceChange: 0,
    aiScore: 72,
    aiLabel: "Competitive",
    aiColor: "text-blue-700 bg-blue-50",
    suggestedOffer: [618000, 635000],
    marketTrend: "hot",
    reduced: false,
    status: "Active",
  },
  {
    id: "3",
    address: "4521 N Ashland Ave",
    city: "Chicago",
    state: "IL",
    zip: "60640",
    price: 359000,
    beds: 2,
    baths: 1,
    sqft: 1200,
    dom: 28,
    agent: "Mike Torres",
    agentName: "Mike Torres",
    agentPhone: "(312) 555-0847",
    agentEmail: "m.torres@remax.com",
    brokerage: "RE/MAX",
    img: ext(3, 600, 400),
    photos: p(3, 'kitchen', 3),
    type: "Condo",
    priceHistory: "reduced",
    priceChange: -20000,
    aiScore: 91,
    aiLabel: "Best Deal",
    aiColor: "text-blue-700 bg-blue-50",
    suggestedOffer: [345000, 360000],
    marketTrend: "cooling",
    reduced: true,
    status: "Active",
  },
  {
    id: "4",
    address: "3102 W Belmont Ave",
    city: "Chicago",
    state: "IL",
    zip: "60618",
    price: 549000,
    beds: 3,
    baths: 2,
    sqft: 2100,
    dom: 3,
    agent: "Donna Keller",
    agentName: "Donna Keller",
    agentPhone: "(312) 555-0223",
    agentEmail: "d.keller@compass.com",
    brokerage: "Compass",
    img: ext(4, 600, 400),
    photos: p(4, 'kitchen', 4),
    type: "Single Family",
    priceHistory: "increased",
    priceChange: 10000,
    aiScore: 65,
    aiLabel: "Act Fast",
    aiColor: "text-blue-700 bg-blue-50",
    suggestedOffer: [545000, 565000],
    marketTrend: "hot",
    reduced: false,
    status: "Active",
  },
  {
    id: "5",
    address: "7845 S Cottage Grove Ave",
    city: "Chicago",
    state: "IL",
    zip: "60619",
    price: 229000,
    beds: 3,
    baths: 1.5,
    sqft: 1600,
    dom: 45,
    agent: "James Wu",
    agentName: "James Wu",
    agentPhone: "(312) 555-0519",
    agentEmail: "j.wu@atproperties.com",
    brokerage: "@properties",
    img: ext(5, 600, 400),
    photos: p(5, 'kitchen', 5),
    type: "Single Family",
    priceHistory: "reduced",
    priceChange: -25000,
    aiScore: 95,
    aiLabel: "Negotiate!",
    aiColor: "text-blue-700 bg-blue-50",
    suggestedOffer: [210000, 225000],
    marketTrend: "cooling",
    reduced: true,
    status: "Pending",
  },
  {
    id: "6",
    address: "1234 W Fullerton Ave",
    city: "Chicago",
    state: "IL",
    zip: "60614",
    price: 795000,
    beds: 4,
    baths: 3,
    sqft: 3200,
    dom: 8,
    agent: "Rachel Bloom",
    agentName: "Rachel Bloom",
    agentPhone: "(312) 555-0761",
    agentEmail: "r.bloom@sothebys.com",
    brokerage: "Sotheby's",
    img: ext(6, 600, 400),
    photos: p(6, 'kitchen', 6),
    type: "Single Family",
    priceHistory: "same",
    priceChange: 0,
    aiScore: 78,
    aiLabel: "Well-Priced",
    aiColor: "text-blue-700 bg-blue-50",
    suggestedOffer: [785000, 810000],
    marketTrend: "hot",
    reduced: false,
    status: "Active",
  },
  {
    id: "7",
    address: "2156 N Damen Ave",
    city: "Chicago",
    state: "IL",
    zip: "60647",
    price: 699000,
    beds: 3,
    baths: 2.5,
    sqft: 2050,
    dom: 6,
    agent: "Tom Nguyen",
    agentName: "Tom Nguyen",
    agentPhone: "(312) 555-0384",
    agentEmail: "t.nguyen@compass.com",
    brokerage: "Compass",
    img: ext(7, 600, 400),
    photos: p(7, 'kitchen', 7),
    type: "Townhouse",
    priceHistory: "same",
    priceChange: 0,
    aiScore: 76,
    aiLabel: "Well-Priced",
    aiColor: "text-blue-700 bg-blue-50",
    suggestedOffer: [688000, 712000],
    marketTrend: "hot",
    reduced: false,
    status: "Active",
  },
  {
    id: "8",
    address: "540 N Lake Shore Dr, Unit 2104",
    city: "Chicago",
    state: "IL",
    zip: "60611",
    price: 1150000,
    beds: 2,
    baths: 2,
    sqft: 1550,
    dom: 21,
    agent: "Patricia Novak",
    agentName: "Patricia Novak",
    agentPhone: "(312) 555-0903",
    agentEmail: "p.novak@jll.com",
    brokerage: "JLL Residential",
    img: ext(8, 600, 400),
    photos: p(8, 'kitchen', 8),
    type: "Condo",
    priceHistory: "reduced",
    priceChange: -50000,
    aiScore: 82,
    aiLabel: "Great Value",
    aiColor: "text-blue-700 bg-blue-50",
    suggestedOffer: [1100000, 1160000],
    marketTrend: "neutral",
    reduced: true,
    status: "Active",
  },
  {
    id: "9",
    address: "1703 W Byron St",
    city: "Chicago",
    state: "IL",
    zip: "60613",
    price: 415000,
    beds: 2,
    baths: 2,
    sqft: 1400,
    dom: 18,
    agent: "Carlos Reyes",
    agentName: "Carlos Reyes",
    agentPhone: "(312) 555-0628",
    agentEmail: "c.reyes@bairdwarner.com",
    brokerage: "Baird & Warner",
    img: ext(9, 600, 400),
    photos: p(9, 'kitchen', 9),
    type: "Condo",
    priceHistory: "same",
    priceChange: 0,
    aiScore: 84,
    aiLabel: "Great Value",
    aiColor: "text-blue-700 bg-blue-50",
    suggestedOffer: [405000, 422000],
    marketTrend: "neutral",
    reduced: false,
    status: "Active",
  },
  {
    id: "10",
    address: "6312 N Glenwood Ave",
    city: "Chicago",
    state: "IL",
    zip: "60660",
    price: 520000,
    beds: 4,
    baths: 2,
    sqft: 2300,
    dom: 33,
    agent: "Amy Chen",
    agentName: "Amy Chen",
    agentPhone: "(773) 555-0114",
    agentEmail: "a.chen@coldwellbanker.com",
    brokerage: "Coldwell Banker",
    img: ext(10, 600, 400),
    photos: p(10, 'kitchen', 10),
    type: "Multi-Family",
    priceHistory: "reduced",
    priceChange: -15000,
    aiScore: 89,
    aiLabel: "Best Deal",
    aiColor: "text-blue-700 bg-blue-50",
    suggestedOffer: [505000, 525000],
    marketTrend: "cooling",
    reduced: true,
    status: "Active",
  },
  {
    id: "11",
    address: "819 W Oakdale Ave",
    city: "Chicago",
    state: "IL",
    zip: "60657",
    price: 875000,
    beds: 5,
    baths: 3.5,
    sqft: 3800,
    dom: 4,
    agent: "Scott Harmon",
    agentName: "Scott Harmon",
    agentPhone: "(312) 555-0277",
    agentEmail: "s.harmon@atproperties.com",
    brokerage: "@properties",
    img: ext(11, 600, 400),
    photos: p(11, 'kitchen', 11),
    type: "Single Family",
    priceHistory: "same",
    priceChange: 0,
    aiScore: 70,
    aiLabel: "Competitive",
    aiColor: "text-blue-700 bg-blue-50",
    suggestedOffer: [865000, 895000],
    marketTrend: "hot",
    reduced: false,
    status: "Active",
  },
  {
    id: "12",
    address: "448 W Dickens Ave",
    city: "Chicago",
    state: "IL",
    zip: "60614",
    price: 339000,
    beds: 1,
    baths: 1,
    sqft: 900,
    dom: 14,
    agent: "Nina Patel",
    agentName: "Nina Patel",
    agentPhone: "(312) 555-0461",
    agentEmail: "n.patel@redfin.com",
    brokerage: "Redfin",
    img: ext(12, 600, 400),
    photos: p(12, 'kitchen', 12),
    type: "Condo",
    priceHistory: "same",
    priceChange: 0,
    aiScore: 80,
    aiLabel: "Well-Priced",
    aiColor: "text-blue-700 bg-blue-50",
    suggestedOffer: [330000, 345000],
    marketTrend: "neutral",
    reduced: false,
    status: "Active",
  },
  {
    id: "13",
    address: "2901 W Diversey Ave",
    city: "Chicago",
    state: "IL",
    zip: "60647",
    price: 469000,
    beds: 3,
    baths: 2,
    sqft: 1750,
    dom: 9,
    agent: "Kevin Walsh",
    agentName: "Kevin Walsh",
    agentPhone: "(773) 555-0852",
    agentEmail: "k.walsh@koenig-rubloff.com",
    brokerage: "Berkshire Hathaway HS",
    img: ext(13, 600, 400),
    photos: p(13, 'kitchen', 13),
    type: "Single Family",
    priceHistory: "reduced",
    priceChange: -10000,
    aiScore: 86,
    aiLabel: "Great Value",
    aiColor: "text-blue-700 bg-blue-50",
    suggestedOffer: [460000, 480000],
    marketTrend: "neutral",
    reduced: true,
    status: "Active",
  },
  {
    id: "14",
    address: "5527 S Woodlawn Ave",
    city: "Chicago",
    state: "IL",
    zip: "60637",
    price: 289000,
    beds: 3,
    baths: 2,
    sqft: 1900,
    dom: 52,
    agent: "Diana Moore",
    agentName: "Diana Moore",
    agentPhone: "(773) 555-0338",
    agentEmail: "d.moore@remax.com",
    brokerage: "RE/MAX",
    img: ext(14, 600, 400),
    photos: p(14, 'kitchen', 14),
    type: "Single Family",
    priceHistory: "reduced",
    priceChange: -35000,
    aiScore: 93,
    aiLabel: "Negotiate!",
    aiColor: "text-blue-700 bg-blue-50",
    suggestedOffer: [265000, 285000],
    marketTrend: "cooling",
    reduced: true,
    status: "Sold",
  },
  {
    id: "15",
    address: "350 W Hubbard St, Unit 606",
    city: "Chicago",
    state: "IL",
    zip: "60654",
    price: 575000,
    beds: 2,
    baths: 2,
    sqft: 1300,
    dom: 16,
    agent: "Marcus Bell",
    agentName: "Marcus Bell",
    agentPhone: "(312) 555-0995",
    agentEmail: "m.bell@compass.com",
    brokerage: "Compass",
    img: ext(15, 600, 400),
    photos: p(15, 'kitchen', 15),
    type: "Condo",
    priceHistory: "same",
    priceChange: 0,
    aiScore: 75,
    aiLabel: "Well-Priced",
    aiColor: "text-blue-700 bg-blue-50",
    suggestedOffer: [565000, 588000],
    marketTrend: "neutral",
    reduced: false,
    status: "Active",
  },
];

/**
 * Returns all properties. Stub for the future database query.
 */
export async function getProperties(): Promise<Property[]> {
  return ALL_PROPERTIES;
}

/**
 * Returns a single property by id, or undefined if not found.
 */
export function getPropertyById(id: string): Property | undefined {
  return ALL_PROPERTIES.find((p) => p.id === id);
}
