import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import Link from "next/link";
import { Shield, FileText, Lock, Scale } from "lucide-react";

const legalPages = [
  {
    icon: FileText,
    title: "Terms of Service",
    desc: "The terms governing your use of HomeOfferDirect.org, including user responsibilities, acceptable use, and limitations of liability.",
    href: "/legal/terms",
    color: "bg-blue-50 text-blue-600",
  },
  {
    icon: Lock,
    title: "Privacy Policy",
    desc: "How we collect, use, store, and protect your personal information, including data sharing practices and your rights.",
    href: "/legal/privacy",
    color: "bg-purple-50 text-purple-600",
  },
  {
    icon: Scale,
    title: "Legal Disclaimer",
    desc: "Important information about the nature of HomeOfferDirect as a document automation tool — not a law firm or real estate agency.",
    href: "/legal/disclaimer",
    color: "bg-amber-50 text-amber-600",
  },
  {
    icon: Shield,
    title: "Cookie Policy",
    desc: "Information about the cookies and tracking technologies we use to improve your experience on our platform.",
    href: "/legal",
    color: "bg-green-50 text-green-600",
  },
];

export default function LegalPage() {
  return (
    <div className="min-h-screen">
      <Navbar />

      <section className="pt-28 pb-16 gradient-bg-soft">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 text-center">
          <h1 className="text-4xl font-extrabold text-slate-900 mb-4">
            Legal & <span className="gradient-text">Compliance</span>
          </h1>
          <p className="text-xl text-slate-500">
            HomeOfferDirect is committed to transparency, user protection, and legal compliance.
          </p>
        </div>
      </section>

      <section className="py-16">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          {/* Important disclaimer */}
          <div className="bg-amber-50 border border-amber-200 rounded-2xl p-6 mb-10">
            <div className="flex gap-4">
              <Scale className="w-6 h-6 text-amber-600 flex-shrink-0 mt-0.5" />
              <div>
                <h2 className="font-bold text-amber-900 mb-2">Important: Not a Law Firm</h2>
                <p className="text-amber-800 text-sm leading-relaxed">
                  HomeOfferDirect.org is a document automation and educational technology platform. We
                  are NOT a law firm, we do NOT provide legal advice, and we do NOT represent you as
                  a real estate agent or attorney. All documents generated by HomeOfferDirect are
                  based on publicly available state-approved forms and are provided for informational
                  and automation purposes only. We strongly encourage all users to have their
                  documents reviewed by a licensed real estate attorney in their state before
                  submission.
                </p>
              </div>
            </div>
          </div>

          {/* Legal pages grid */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 mb-12">
            {legalPages.map(({ icon: Icon, title, desc, href, color }) => (
              <Link
                key={title}
                href={href}
                className="bg-white rounded-2xl border border-slate-100 shadow-sm p-6 hover:shadow-md hover:border-blue-200 transition-all group"
              >
                <div className={`w-12 h-12 ${color} rounded-xl flex items-center justify-center mb-4`}>
                  <Icon className="w-6 h-6" />
                </div>
                <h3 className="font-bold text-slate-900 mb-2 group-hover:text-blue-600 transition-colors">
                  {title}
                </h3>
                <p className="text-sm text-slate-500 leading-relaxed">{desc}</p>
              </Link>
            ))}
          </div>

          {/* State compliance section */}
          <div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-8">
            <h2 className="text-xl font-bold text-slate-900 mb-4">State Compliance</h2>
            <p className="text-slate-600 mb-6 text-sm leading-relaxed">
              HomeOfferDirect uses state-approved real estate forms sourced from official state real
              estate commissions and recognized real estate associations. Our compliance team reviews
              and updates all forms when state regulations change.
            </p>
            <div className="grid grid-cols-2 sm:grid-cols-5 gap-3">
              {[
                { state: "Illinois", note: "CAR Forms" },
                { state: "Texas", note: "TREC Forms" },
                { state: "New York", note: "NYSBA Forms" },
                { state: "California", note: "CAR Forms" },
                { state: "Florida", note: "FAR Forms" },
              ].map(({ state, note }) => (
                <div key={state} className="bg-slate-50 rounded-xl p-3 text-center border border-slate-100">
                  <p className="text-sm font-semibold text-slate-900">{state}</p>
                  <p className="text-xs text-slate-400 mt-0.5">{note}</p>
                </div>
              ))}
            </div>
          </div>

          <p className="text-center text-xs text-slate-400 mt-8 leading-relaxed">
            Questions about our legal documents or compliance? Contact us at{" "}
            <a href="mailto:legal@homeofferdirect.org" className="text-blue-500 hover:underline">
              legal@homeofferdirect.org
            </a>
          </p>
        </div>
      </section>

      <Footer />
    </div>
  );
}
