"use client";
import { useState } from "react";
import { Sparkles, X } from "lucide-react";

interface AiBadgeProps {
  label?: string;
  tooltip?: string;
}

export default function AiBadge({ label = "AI-generated", tooltip }: AiBadgeProps) {
  const [open, setOpen] = useState(false);
  const defaultTooltip = "This content was generated by an AI model. It is based on available market data and offer parameters. Always verify AI-generated content before relying on it for important decisions.";

  return (
    <span style={{ display: "inline-flex", alignItems: "center", gap: 4, position: "relative" }}>
      <button
        onClick={() => setOpen(v => !v)}
        style={{
          display: "inline-flex", alignItems: "center", gap: 4,
          fontSize: 10, fontWeight: 700, color: "#1d4ed8",
          background: "#dbeafe", border: "1px solid #93c5fd",
          borderRadius: 99, padding: "2px 8px", cursor: "pointer",
        }}
        aria-label="AI-generated content — click for details"
      >
        <Sparkles style={{ width: 9, height: 9 }} />
        {label}
      </button>

      {open && (
        <>
          <div style={{ position: "fixed", inset: 0, zIndex: 100 }} onClick={() => setOpen(false)} />
          <div style={{
            position: "absolute", zIndex: 101, bottom: "calc(100% + 8px)", left: "50%",
            transform: "translateX(-50%)", width: 260,
            background: "#1e293b", color: "#f1f5f9",
            borderRadius: 10, padding: "12px 14px",
            fontSize: 12, lineHeight: 1.6, fontWeight: 400,
            boxShadow: "0 8px 24px -4px rgba(0,0,0,0.35)",
          }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 6 }}>
              <span style={{ fontWeight: 700, fontSize: 12 }}>AI-generated content</span>
              <button onClick={() => setOpen(false)} style={{ background: "none", border: "none", color: "#94a3b8", cursor: "pointer", padding: 0 }}>
                <X style={{ width: 12, height: 12 }} />
              </button>
            </div>
            <p style={{ margin: "0 0 8px" }}>{tooltip ?? defaultTooltip}</p>
            <a href="/transparency" style={{ color: "#60a5fa", fontSize: 11 }}>AI labeling policy →</a>
            <div style={{
              position: "absolute", top: "100%", left: "50%", transform: "translateX(-50%)",
              width: 0, height: 0,
              borderLeft: "6px solid transparent", borderRight: "6px solid transparent",
              borderTop: "6px solid #1e293b",
            }} />
          </div>
        </>
      )}
    </span>
  );
}
